---
- name: LAYER 2 - Create VLAN Database (Legacy Mode)
  hosts: switches  # Chạy trên Group tổng (Gồm Core và 3 Access)
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create VLAN 50 (User)
      cisco.ios.ios_config:
        lines:
          - name User_VLAN
        parents: vlan 50

    - name: Create VLAN 60 (Server)
      cisco.ios.ios_config:
        lines:
          - name Server_VLAN
        parents: vlan 60

    - name: Create VLAN 100 (Mgmt)
      cisco.ios.ios_config:
        lines:
          - name Mgmt_VLAN
        parents: vlan 100
        
    - name: Create VLAN 999 (Uplink Firewall)
      cisco.ios.ios_config:
        lines:
          - name Uplink_FW
        parents: vlan 999

    - name: Save Configuration
      cisco.ios.ios_command:
        commands: write memory
