---
- name: LAYER 2 - Create VLAN Database
  hosts: switches  # Chạy trên Group tổng (Chứa cả Core và 3 Access)
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create Standard VLANs
      cisco.ios.ios_vlans:
        config:
          - name: User_VLAN
            vlan_id: 50
          - name: Server_VLAN
            vlan_id: 60
          - name: Mgmt_VLAN
            vlan_id: 100
        state: merged
        
    - name: Save Config
      cisco.ios.ios_command:
        commands: write memory
