---
- name: Configure AD & DNS (Compatible V3 - PowerShell Native)
  hosts: ad_server
  gather_facts: no
  vars:
    domain_dn: "DC=nhan,DC=local"
    gateway_ip: "192.168.60.1"
    sso_account: "svc-webserver"
    
    # Danh sách DNS
    dns_records:
      - { name: "intranet", value: "192.168.60.100" }
      - { name: "web1",     value: "192.168.60.100" }
      - { name: "webserver",value: "192.168.60.100" }
      - { name: "fileserver",value: "192.168.60.101" }

  tasks:
    # -------------------------------------------------------------
    # 1. CẤU HÌNH MẠNG (Sửa lỗi 'next_hop' thành 'gateway')
    # -------------------------------------------------------------
    - name: Ensure Default Gateway is Core Switch
      ansible.windows.win_route:
        destination: 0.0.0.0/0
        gateway: "{{ gateway_ip }}"  # <-- Đã sửa 'next_hop' thành 'gateway'
        metric: 1
        state: present

    # -------------------------------------------------------------
    # 2. CẤU HÌNH DNS FORWARDER (PowerShell)
    # -------------------------------------------------------------
    - name: Configure DNS Forwarders (Google 8.8.8.8)
      ansible.windows.win_shell: |
        $F = Get-DnsServerForwarder
        If ($F.IPAddress -notcontains "8.8.8.8") { Set-DnsServerForwarder -IPAddress "8.8.8.8" -PassThru }
        If ($F.IPAddress -contains "192.168.31.2") { Remove-DnsServerForwarder -IPAddress "192.168.31.2" -Force }
      changed_when: false

    # -------------------------------------------------------------
    # 3. QUẢN LÝ DNS RECORDS (Module có sẵn)
    # -------------------------------------------------------------
    - name: Ensure DNS Records exist
      ansible.windows.win_dns_record:
        name: "{{ item.name }}"
        zone: "nhan.local"
        type: "A"
        value: "{{ item.value }}"
        state: present
      loop: "{{ dns_records }}"

    # -------------------------------------------------------------
    # 4. QUẢN LÝ CẤU TRÚC OU (Dùng PowerShell thuần - Không cần Collection)
    # -------------------------------------------------------------
    - name: Ensure OUs exist (PowerShell)
      ansible.windows.win_shell: |
        $OUName = "{{ item }}"
        $Path = "{{ domain_dn }}"
        if (-not (Get-ADOrganizationalUnit -Filter "Name -eq '$OUName'" -SearchBase $Path -ErrorAction SilentlyContinue)) {
            New-ADOrganizationalUnit -Name $OUName -Path $Path
            Write-Host "Created"
        }
      register: ou_result
      changed_when: "'Created' in ou_result.stdout"
      loop:
        - "Admins"
        - "Computers"
        - "Groups"
        - "Servers"
        - "Users"

    # -------------------------------------------------------------
    # 5. QUẢN LÝ GROUP (PowerShell thuần)
    # -------------------------------------------------------------
    - name: Ensure Groups exist (PowerShell)
      ansible.windows.win_shell: |
        $GroupName = "{{ item }}"
        $Path = "OU=Groups,{{ domain_dn }}"
        if (-not (Get-ADGroup -Filter "Name -eq '$GroupName'" -SearchBase $Path -ErrorAction SilentlyContinue)) {
            New-ADGroup -Name $GroupName -GroupScope Global -GroupCategory Security -Path $Path
            Write-Host "Created"
        }
      register: group_result
      changed_when: "'Created' in group_result.stdout"
      loop:
        - "GG-Users-All"
        - "GG-Dept-IT"
        - "GG-Dept-HR"
        - "GG-Dept-Sale"

    # -------------------------------------------------------------
    # 6. QUẢN LÝ USER SSO & SPN (PowerShell thuần)
    # -------------------------------------------------------------
    - name: Ensure SSO Service Account exists & Configure SPN (PowerShell)
      ansible.windows.win_shell: |
        $User = "{{ sso_account }}"
        $Path = "CN=Users,{{ domain_dn }}" # User svc-webserver của bạn đang ở đây
        $SPN = "HTTP/intranet.nhan.local"

        # 1. Tạo User nếu chưa có
        if (-not (Get-ADUser -Filter "SamAccountName -eq '$User'" -ErrorAction SilentlyContinue)) {
            # Tạo mới với pass mặc định
            New-ADUser -Name $User -SamAccountName $User -Path $Path -Enabled $true -PasswordNeverExpires $true -AccountPassword (ConvertTo-SecureString "Password@123" -AsPlainText -Force)
            Write-Host "Created_User"
        }

        # 2. Kiểm tra và sửa cấu hình (Pass never expires & SPN)
        $ADUser = Get-ADUser -Identity $User -Properties ServicePrincipalNames, PasswordNeverExpires
        
        if (-not $ADUser.PasswordNeverExpires) {
            Set-ADUser -Identity $User -PasswordNeverExpires $true
            Write-Host "Fixed_Pass"
        }

        if ($ADUser.ServicePrincipalNames -notcontains $SPN) {
            Set-ADUser -Identity $User -ServicePrincipalNames @{Add=$SPN}
            Write-Host "Added_SPN"
        }
      register: sso_result
      changed_when: "'Created_User' in sso_result.stdout or 'Added_SPN' in sso_result.stdout"
