---
- name: Configure Windows 10 Client (Standard Operating Environment)
  hosts: clients  # Group chứa IP các máy Win10
  gather_facts: yes

  vars:
    company_name: "NHAN CORPORATION"
    intranet_site: "intranet.nhan.local"
    fileserver_path: "\\fileserver\Public"

  tasks:
    # -------------------------------------------------------------
    # 1. CÀI ĐẶT PHẦN MỀM CƠ BẢN (Dùng Chocolatey)
    # -------------------------------------------------------------
    - name: Install Chocolatey (Trình quản lý gói)
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Essential Software (Chrome, 7zip, Notepad++)
      win_chocolatey:
        name:
          - googlechrome
          - 7zip
          - notepadplusplus
        state: present

    # -------------------------------------------------------------
    # 2. CẤU HÌNH SSO CHO TRÌNH DUYỆT (Sửa lỗi hỏi password)
    # -------------------------------------------------------------
    # Thêm domain nhan.local vào "AuthNegotiateDelegateWhitelist" của Chrome/Edge
    # Điều này ép trình duyệt gửi vé Kerberos cho web server
    - name: Configure Chrome/Edge for Kerberos SSO
      ansible.windows.win_regedit:
        path: HKLM\SOFTWARE\Policies\Google\Chrome
        name: AuthNegotiateDelegateWhitelist
        data: "*.nhan.local"
        type: string
        state: present

    - name: Configure Edge for Kerberos SSO
      ansible.windows.win_regedit:
        path: HKLM\SOFTWARE\Policies\Microsoft\Edge
        name: AuthNegotiateDelegateWhitelist
        data: "*.nhan.local"
        type: string
        state: present

    # -------------------------------------------------------------
    # 3. MAP Ổ ĐĨA MẠNG (Ổ P: PUBLIC)
    # -------------------------------------------------------------
    - name: Map Public Drive (P:) persistently
      community.windows.win_mapped_drive:
        letter: P
        path: "{{ fileserver_path }}"
        state: present
        persistence: permanent
      # Lưu ý: Task này thường chạy dưới context người dùng (become: no) 
      # hoặc chạy qua Logon Script nếu chạy bằng Admin.

    # -------------------------------------------------------------
    # 4. TẠO THÔNG BÁO ĐĂNG NHẬP (LEGAL NOTICE)
    # -------------------------------------------------------------
    - name: Set Legal Notice Caption
      ansible.windows.win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticecaption
        data: "Chào mừng đến với {{ company_name }}"
        type: string

    - name: Set Legal Notice Text
      ansible.windows.win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticetext
        data: "Hệ thống này được giám sát. Vui lòng tuân thủ chính sách bảo mật thông tin."
        type: string
