---
- name: Deploy Intranet Portal + Kerberos SSO (nhan.local) – Version Hoàn Chỉnh
  hosts: webserver
  become: yes
  vars:
    keytab_path: /etc/apache2/webserver.keytab
    smb_server_ip: 192.168.60.101
    domain_realm: NHAN.LOCAL

  tasks:
    - name: Cài đặt packages cần thiết
      apt:
        name:
          - libapache2-mod-auth-gssapi
          - krb5-user
          - sssd
          - sssd-tools
          - realmd
          - adcli
        state: present
        update_cache: yes

    - name: Copy keytab từ GitHub (files/webserver.keytab)
      copy:
        src: files/webserver.keytab
        dest: "{{ keytab_path }}"
        owner: root
        group: root
        mode: '0600'  # Chỉ root đọc được
      notify: restart apache2

    - name: Đảm bảo thư mục intranet tồn tại
      file:
        path: /var/www/intranet
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy index.php hoàn chỉnh với fallback 3 user (Nhan-IT, Hai-HR, Lan-Sale)
      copy:
        content: |
          <?php
          // Lấy REMOTE_USER từ Kerberos SSO
          $raw = $_SERVER['REMOTE_USER'] ?? 'Khách';
          $user = "Khách";
          if (strpos($raw, '@') !== false) {
              $user = strtolower(explode('@', $raw)[0]);
          } elseif (strpos($raw, '\\') !== false) {
              $user = strtolower(explode('\\', $raw)[1]);
          } else {
              $user = strtolower($raw);
          }
          $display_name = ucfirst($user);
          ?>
          <!DOCTYPE html>
          <html lang="vi">
          <head>
              <meta charset="UTF-8">
              <title>Intranet - NHAN CORPORATION</title>
              <style>
                  body { font-family: Segoe UI, Arial, sans-serif; background: #f4f7fa; margin: 0; padding: 0; }
                  .container { max-width: 700px; margin: 0 auto; padding: 20px; }
                  h1 { text-align: center; color: #0066cc; margin-top: 80px; }
                  h2 { text-align: center; color: #333; }
                  h3 { text-align: center; color: #444; margin-top: 50px; }
                  ul { list-style: none; padding: 0; text-align: center; }
                  li { margin: 15px 0; }
                  a { color: #0066cc; font-size: 1.6em; text-decoration: none; font-weight: bold; }
                  a:hover { text-decoration: underline; }
                  .guest { color: #999; text-align: center; margin-top: 60px; font-size: 1.1em; }
              </style>
          </head>
          <body>
          <div class="container">
              <h1>NHAN CORPORATION</h1>
              <h2>Xin chào <b><?= htmlspecialchars($display_name) ?>!</b></h2>

              <h3>Thư mục bạn được phép truy cập:</h3>
              <ul>
          <?php
          // Fallback hardcode cho 3 user (dễ test logout/login)
          $folders = ['Public']; // GG-User-All
          if ($user === 'nhan') $folders[] = 'IT';
          elseif ($user === 'hai') $folders[] = 'HR';
          elseif ($user === 'lan') $folders[] = 'Sale';

          // Kiểm tra group thật (nếu Kerberos hoạt động)
          if ($user !== 'khách') {
              $principal = $user . '@nhan.local';
              if (shell_exec("getent group 'GG-Dept-IT'   | grep -Fq '$principal'") === '0') $folders[] = 'IT';
              if (shell_exec("getent group 'GG-Dept-HR'   | grep -Fq '$principal'") === '0') $folders[] = 'HR';
              if (shell_exec("getent group 'GG-Dept-Sale' | grep -Fq '$principal'") === '0') $folders[] = 'Sale';
          }

          $folders = array_unique($folders);
          foreach ($folders as $folder) {
              echo "<li><a href=\"\\\\\\\\$smb_server_ip\\$folder\" target=\"_blank\">📁 $folder</a></li>";
          }
          ?>
              </ul>

          <?php if ($user === "Khách") { ?>
              <p class='guest'>Bạn đang truy cập với tư cách khách.<br>
              Vui lòng <b>đăng xuất</b> Windows và đăng nhập lại bằng tài khoản:<br>
              <b>Nhan</b> (IT) • <b>Hai</b> (HR) • <b>Lan</b> (Sale)</p>
          <?php } ?>
          </div>
          </body>
          </html>
        dest: /var/www/intranet/index.php
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart apache2

    - name: Deploy VirtualHost chuẩn mod_auth_gssapi (intranet.conf)
      template:
        src: templates/intranet.conf.j2
        dest: /etc/apache2/sites-available/intranet.conf
        mode: '0644'
      notify: restart apache2

    - name: Force Enable Apache Modules (rewrite & auth_gssapi)
      shell: a2enmod rewrite auth_gssapi
      register: mod_result
      changed_when: "'Enabling module' in mod_result.stdout"
      notify: restart apache2

    # Task này chỉ bật site
    - name: Kích hoạt Intranet Site
      shell: |
        a2dissite 000-default.conf || true
        a2ensite intranet.conf
      args:
        creates: /etc/apache2/sites-enabled/intranet.conf
      notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
