---
- name: Configure SMB Shares via Native PowerShell (Manual Method)
  hosts: fileserver
  gather_facts: no

  vars:
    share_root: 'C:\CompanyShare'
    domain_netbios: 'NHAN'

    # Giữ nguyên cấu trúc biến đơn giản của bạn
    department_shares:
      - name: Public
        folder: Public
        groups_rw: ['NHAN\GG-Users-All']
      - name: IT
        folder: IT
        groups_rw: ['NHAN\GG-Dept-IT']
      - name: HR
        folder: HR
        groups_rw: ['NHAN\GG-Dept-HR']
      - name: Sale
        folder: Sale
        groups_rw: ['NHAN\GG-Dept-Sale']

  tasks:
    # 1. Tạo thư mục gốc và thư mục con (Phần này win_file làm tốt, giữ lại)
    - name: Ensure folders exist
      ansible.windows.win_file:
        path: "{{ share_root }}\\{{ item.folder }}"
        state: directory
      loop: "{{ department_shares }}"

    # 2. Setup NTFS (Phần này bạn đã chạy ổn, giữ lại cho bảo mật)
    - name: Set NTFS Permissions (Modify for Groups)
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.0.folder }}"
        user: "{{ item.1 }}"
        rights: modify
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # 3. Setup SMB bằng PowerShell (THAY THẾ win_share)
    # Đây chính là cách "làm thủ công" nhưng được tự động hóa
    - name: Force Re-create SMB Share using PowerShell
      ansible.windows.win_shell: |
        $ShareName = "{{ item.name }}"
        $Path = "{{ share_root }}\{{ item.folder }}"
        
        # Danh sách Admin (Full Control)
        $FullUsers = @("{{ domain_netbios }}\Domain Admins", "BUILTIN\Administrators")
        
        # Danh sách Group (Change Access) - Lấy từ biến Ansible đưa vào
        $ChangeUsers = @("{{ item.groups_rw | join('","') }}")

        # BƯỚC 1: Xóa Share cũ thẳng tay (nếu có)
        if (Get-SmbShare -Name $ShareName -ErrorAction SilentlyContinue) {
            Remove-SmbShare -Name $ShareName -Force
        }

        # BƯỚC 2: Tạo Share mới tinh với đúng quyền (Clean Install)
        # Lệnh này tương đương việc bạn click chuột chọn quyền thủ công
        New-SmbShare -Name $ShareName -Path $Path -FullAccess $FullUsers -ChangeAccess $ChangeUsers -Description "$ShareName Department Share"

      loop: "{{ department_shares }}"
      # register: debug_output  <-- Bật cái này nếu muốn xem log chi tiết
