---
- name: Configure Windows File Server shares
  hosts: fileserver
  gather_facts: no

  vars:
    share_root: 'C:\CompanyShare'
    domain_netbios: 'NHAN'

    department_shares:
      - name: Public
        folder: Public
        groups_rw:
          - 'GG-Users-All'
      - name: IT
        folder: IT
        groups_rw:
          - 'GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw:
          - 'GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw:
          - 'GG-Dept-Sale'

  tasks:

    # 0. XÓA SHARE CŨ ĐỂ KHÔNG CÒN "EVERYONE DENY"
    - name: Remove old SMB share (if exists)
      ansible.windows.win_shell: >
        Remove-SmbShare -Name {{ item.name }} -Force -ErrorAction SilentlyContinue
      loop: "{{ department_shares }}"

    # 1. Tạo thư mục gốc
    - name: Ensure root share folder exists
      ansible.windows.win_file:
        path: "{{ share_root }}"
        state: directory

    # 2. Tạo thư mục con
    - name: Create subfolders for each department
      ansible.windows.win_file:
        path: "{{ share_root }}\\{{ item.folder }}"
        state: directory
      loop: "{{ department_shares }}"

    # 3. Set NTFS Permission cho đúng group
    - name: Set NTFS ACL for RW groups
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.0.folder }}"
        user: "{{ domain_netbios }}\\{{ item.1 }}"
        rights: modify
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # 4. Set Full cho Domain Admins + Administrators
    - name: Add Full Access for Admins
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.folder }}"
        user: "{{ domain_netbios }}\\Domain Admins"
        rights: full
        type: allow
        state: present
      loop: "{{ department_shares }}"

    # 5. Tạo SMB Share MỚI HOÀN TOÀN (đã xoá cũ)
    - name: Create SMB share with correct permissions
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        state: present
        full_access:
          - "{{ domain_netbios }}\\Domain Admins"
          - "BUILTIN\\Administrators"
        change_access: >-
          {{
            item.groups_rw
            | map('regex_replace', '^(.*)$', domain_netbios ~ '\\\\' ~ '\1')
            | list
          }}
        description: "{{ item.name }} Department Share"
      loop: "{{ department_shares }}"
