---
- name: Configure Windows File Server shares
  hosts: fileserver
  gather_facts: no

  vars:
    # Thư mục gốc chứa các thư mục chia sẻ
    share_root: 'C:\CompanyShare'

    # NetBIOS name của domain (nhan.local -> NHAN)
    domain_netbios: 'NHAN'

    # Danh sách các share cần tạo
    department_shares:
      - name: Public
        folder: Public
        groups_rw:
          - 'GG-Users-All'      # mọi user
      - name: IT
        folder: IT
        groups_rw:
          - 'GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw:
          - 'GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw:
          - 'GG-Dept-Sale'

  tasks:
    - name: Ensure root share folder exists
      ansible.windows.win_file:
        path: '{{ share_root }}'
        state: directory

    - name: Create subfolders for each department
      ansible.windows.win_file:
        path: '{{ share_root }}\{{ item.folder }}'
        state: directory
      loop: '{{ department_shares }}'

    # NTFS ACL: gán quyền Modify cho các group AD tương ứng
    - name: Set NTFS ACL for RW groups on each folder
      ansible.windows.win_acl:
        path: '{{ share_root }}\{{ item.0.folder }}'
        user: '{{ domain_netbios }}\{{ item.1 }}'
        rights: modify
        type: allow
        state: present
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # Tạo SMB share tương ứng cho mỗi thư mục
    - name: Create SMB shares
      win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        change_access: "{{ item.groups_rw | join(',') }}"
        description: "{{ item.name }} Department Share"
        state: present
      loop: "{{ department_shares }}"

