---
- name: Configure Windows File Server shares
  hosts: fileserver
  gather_facts: no

  vars:
    share_root: 'C:\CompanyShare'
    domain_netbios: 'NHAN'   # NetBIOS name của domain

    department_shares:
      - name: Public
        folder: Public
        groups_rw:
          - 'GG-Users-All'
      - name: IT
        folder: IT
        groups_rw:
          - 'GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw:
          - 'GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw:
          - 'GG-Dept-Sale'

  tasks:
    - name: Ensure root share folder exists
      ansible.windows.win_file:
        path: '{{ share_root }}'
        state: directory

    - name: Create subfolders for each department
      ansible.windows.win_file:
        path: '{{ share_root }}\{{ item.folder }}'
        state: directory
      loop: '{{ department_shares }}'

    # --- NTFS ACL: cấp quyền Modify cho domain groups ---
    - name: Set NTFS ACL for RW groups on each folder
      ansible.windows.win_acl:
        path: '{{ share_root }}\{{ item.0.folder }}'
        user: '{{ domain_netbios }}\{{ item.1 }}'
        rights: modify
        type: allow
        state: present
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # --- Dọn ACL share cũ: xóa Everyone nếu có ---
    - name: Remove Everyone access from SMB share if exists
      ansible.windows.win_shell: >
        Revoke-SmbShareAccess -Name {{ item.name }}
        -AccountName Everyone -Force -ErrorAction SilentlyContinue
      loop: "{{ department_shares }}"

    # --- Tạo SMB share với domain groups ---
    - name: Create SMB shares with domain groups
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        description: "{{ item.name }} Department Share"
        state: present
        change_access: >-
          {{
            item.groups_rw
            | map('regex_replace','^(.*)$', domain_netbios ~ '\\\\' ~ '\1')
            | list
          }}
        full_access:
          - "{{ domain_netbios }}\\Domain Admins"
          - "BUILTIN\\Administrators"
      loop: "{{ department_shares }}"

