---
- name: Configure Windows File Server shares
  hosts: fileserver
  gather_facts: no

  vars:
    # Thư mục gốc chứa các share
    share_root: 'C:\CompanyShare'

    # NetBIOS domain name (nhan.local -> NHAN)
    domain_netbios: 'NHAN'

    # Định nghĩa các share
    department_shares:
      - name: Public
        folder: Public
        groups_rw:
          - 'GG-Users-All'      # tất cả user
      - name: IT
        folder: IT
        groups_rw:
          - 'GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw:
          - 'GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw:
          - 'GG-Dept-Sale'

  tasks:
    # 1. Tạo thư mục gốc
    - name: Ensure root share folder exists
    - ansible.windows.win_file:
        path: '{{ share_root }}'
        state: directory

    # 2. Tạo thư mục con cho từng phòng ban
    - name: Create subfolders for each department
      ansible.windows.win_file:
        path: "{{ share_root }}\\{{ item.folder }}"
        state: directory
      loop: "{{ department_shares }}"

    # 3. Cấp NTFS quyền Modify cho đúng domain group
    - name: Set NTFS ACL for RW groups on each folder
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.0.folder }}"
        user: "{{ domain_netbios }}\\{{ item.1 }}"
        rights: modify
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # 4. Xóa mọi Deny Everyone trên share cũ nếu có
    - name: Remove Everyone access from existing SMB shares (if any)
      ansible.windows.win_shell: >
        Revoke-SmbShareAccess -Name {{ item.name }}
        -AccountName Everyone -Force -ErrorAction SilentlyContinue
      loop: "{{ department_shares }}"

    # 5. Tạo SMB share và gán Change cho domain group
    - name: Create / update SMB shares with domain groups
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        description: "{{ item.name }} Department Share"
        state: present
        # đổi 'GG-Dept-IT' -> 'NHAN\GG-Dept-IT', ...
        change_access: >-
          {{
            item.groups_rw
            | map('regex_replace', '^(.*)$', domain_netbios ~ '\\\\' ~ '\1')
            | list
          }}
        full_access:
          - "{{ domain_netbios }}\\Domain Admins"
          - "BUILTIN\\Administrators"
      loop: "{{ department_shares }}"
