---
- name: Configure Windows File Server shares (FIXED & STABLE)
  hosts: fileserver
  gather_facts: no

  vars:
    share_root: 'C:\CompanyShare'
    domain_netbios: 'NHAN'

    # SỬA LỖI TẠI ĐÂY:
    # Khai báo luôn "DOMAIN\GROUP" ở đây. 
    # Việc này giúp Ansible không phải tính toán cộng chuỗi phức tạp ở bên dưới.
    department_shares:
      - name: Public
        folder: Public
        groups_rw: 
          - 'NHAN\GG-Users-All'
      - name: IT
        folder: IT
        groups_rw: 
          - 'NHAN\GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw: 
          - 'NHAN\GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw: 
          - 'NHAN\GG-Dept-Sale'

  tasks:
    # 0. XÓA SHARE CŨ (Dùng module win_share chuẩn hơn win_shell)
    # Bước này cực quan trọng để xóa quyền "Everyone Deny" do lần chạy lỗi trước để lại
    - name: Remove old SMB share to clear bad permissions
      ansible.windows.win_share:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ department_shares }}"

    # 1. Tạo thư mục gốc
    - name: Ensure root share folder exists
      ansible.windows.win_file:
        path: "{{ share_root }}"
        state: directory

    # 2. Tạo thư mục con
    - name: Create subfolders
      ansible.windows.win_file:
        path: "{{ share_root }}\\{{ item.folder }}"
        state: directory
      loop: "{{ department_shares }}"

    # 3. NTFS: Domain Admins Full Control (Kế thừa từ gốc hoặc set riêng)
    - name: Set Full NTFS for Admins
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.folder }}"
        user: "{{ domain_netbios }}\\Domain Admins"
        rights: full
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares }}"

    # 4. NTFS: Group phòng ban Modify
    # Vì item.1 bây giờ là "NHAN\GG-...", ta dùng trực tiếp không cần ghép chuỗi
    - name: Set Modify NTFS for RW groups
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.0.folder }}"
        user: "{{ item.1 }}" 
        rights: modify
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares | subelements('groups_rw') }}"

    # 5. SMB SHARE (ĐÃ SỬA LỖI)
    # Code bây giờ rất sạch, chỉ việc lấy danh sách groups_rw đắp vào.
    - name: Create SMB share with correct permissions
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        state: present
        description: "{{ item.name }} Department Share"
        
        full_access:
          - "{{ domain_netbios }}\\Domain Admins"
          - "BUILTIN\\Administrators"
        
        # CHÍNH LÀ CHỖ NÀY: Không còn regex, không còn map, không thể sai được nữa.
        change_access: "{{ item.groups_rw }}"
        
        # Đảm bảo không ai khác được quyền đọc (Xóa Everyone)
        read_access: []
      loop: "{{ department_shares }}"
