---
- name: Configure Windows File Server shares & NTFS (chuẩn AD)
  hosts: fileserver
  gather_facts: no

  vars:
    share_root: 'C:\CompanyShare'
    # NetBIOS của domain nhan.local
    domain_netbios: 'NHAN'

    department_shares:
      - name: Public
        folder: Public
        groups_rw:
          - 'GG-Users-All'
      - name: IT
        folder: IT
        groups_rw:
          - 'GG-Dept-IT'
      - name: HR
        folder: HR
        groups_rw:
          - 'GG-Dept-HR'
      - name: Sale
        folder: Sale
        groups_rw:
          - 'GG-Dept-Sale'

  tasks:
    ####################################################################
    # 1. Tạo thư mục gốc + thư mục con
    ####################################################################
    - name: Ensure root share folder exists
      ansible.windows.win_file:
        path: '{{ share_root }}'
        state: directory

    - name: Create subfolders for each department
      ansible.windows.win_file:
        path: "{{ share_root }}\\{{ item.folder }}"
        state: directory
      loop: "{{ department_shares }}"

    ####################################################################
    # 2. NTFS: Domain Admins Full Control trên tất cả thư mục con
    ####################################################################
    - name: Ensure Domain Admins have Full NTFS on each department folder
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.folder }}"
        user: "{{ domain_netbios }}\\Domain Admins"
        rights: full
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares }}"

    ####################################################################
    # 3. NTFS: Group phòng ban có Modify trên thư mục của mình
    ####################################################################
    - name: Ensure RW group has Modify NTFS on its folder
      ansible.windows.win_acl:
        path: "{{ share_root }}\\{{ item.0.folder }}"
        user: "{{ domain_netbios }}\\{{ item.1 }}"
        rights: modify
        type: allow
        state: present
        inherit: "ContainerInherit, ObjectInherit"
        propagation: "None"
      loop: "{{ department_shares | subelements('groups_rw') }}"

    ####################################################################
    # 4. SMB: Bỏ Everyone (nếu còn) để khỏi lệch với chuẩn
    ####################################################################
    - name: Remove Everyone access from existing SMB shares (if present)
      ansible.windows.win_shell: >
        Revoke-SmbShareAccess -Name {{ item.name }}
        -AccountName Everyone -Force -ErrorAction SilentlyContinue
      loop: "{{ department_shares }}"

    ####################################################################
    # 5. SMB: Tạo/cập nhật share với đúng group domain
    ####################################################################
    - name: Create / update SMB shares with correct domain groups
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ share_root }}\\{{ item.folder }}"
        description: "{{ item.name }} Department Share"
        state: present

        # Domain Admins & local Administrators có Full
        full_access:
          - "{{ domain_netbios }}\\Domain Admins"
          - "BUILTIN\\Administrators"

        # Nhóm phòng ban có quyền Change (Modify)
        change_access: >-
          {{
            item.groups_rw
            | map('regex_replace', '^(.*)$', domain_netbios ~ '\\\\' ~ '\1')
            | list
          }}
      loop: "{{ department_shares }}"
