---
- name: tao_vlan
  hosts: SW1
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Create vlan
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: "SALES"
            state: active
          - vlan_id: 20
            name: "IT"
            state: active
          - vlan_id: 30
            name: "MANAGER"
            state: active
        state: merged

    - name: Show vlan
      cisco.ios.ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
