---
- name: tao_vlan
  hosts: all
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Create vlan
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 50
            name: "phong_50"
            state: active
          - vlan_id: 51
            name: "phong_51"
            state: active
          - vlan_id: 52
            name: "phong_52"
            state: active
        state: merged

    - name: Show vlan
      cisco.ios.ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
